packages:
  - apps/*
  - packages/*

catalog:
  '@ant-design/icons-vue': ^7.0.1
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@eslint/js': ^9.39.2
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tsconfig/node24': ^24.0.3
  '@types/crypto-js': ^4.2.2
  '@types/node': ^25.0.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  '@vitejs/plugin-react': ^4.5.2
  '@vitejs/plugin-vue': ^6.0.2
  '@vitejs/plugin-vue-jsx': 5.1.2
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.1.0
  ant-design-vue: ^4.2.6
  autoprefixer: ^10.4.23
  axios: ^1.13.2
  commitizen: ^4.3.1
  concurrently: ^9.1.2
  crypto-js: ^4.2.0
  cz-conventional-changelog: ^3.3.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-vue: ^10.5.1
  h3: ^1.15.4
  husky: ^9.1.7
  lint-staged: ^16.2.7
  msw: ^2.7.5
  nitropack: ^2.10.4
  npm-run-all2: ^8.0.4
  pinia: ^3.0.4
  pinyin-pro: ^3.27.0
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  prettier: ^3.7.4
  qiankun: ^2.10.16
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^7.1.5
  sass: ^1.97.1
  stylelint: ^16.26.1
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.1
  stylelint-config-standard-scss: ^16.0.0
  stylelint-order: ^7.0.0
  tailwindcss: ^4.1.18
  ts-node: ^10.9.2
  typescript: ~5.9.0
  typescript-eslint: ^8.49.0
  unplugin-auto-import: ^20.3.0
  vite: ^7.2.4
  vite-plugin-qiankun: ^1.0.15
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-devtools: 8.0.5
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5
