/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    RightOutlined: typeof import('@ant-design/icons-vue')['RightOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const APopover: typeof import('ant-design-vue/es')['Popover']
  const ASpin: typeof import('ant-design-vue/es')['Spin']
  const ATooltip: typeof import('ant-design-vue/es')['Tooltip']
  const ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
  const CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
  const LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
  const RightOutlined: typeof import('@ant-design/icons-vue')['RightOutlined']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}